repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: db7346d375eda68a0174f2c057dd97f2fbffe030 # frozen: v4.2.0
    hooks:
      - id: check-added-large-files
        args:
          - "--maxkb=10000"
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: ^.vscode/
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: '^(\.gitignore|\.dictionary)$'
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-ensure-ascii"
        # Exclude folders: https://stackoverflow.com/questions/61032281/exclude-some-files-on-running-black-using-pre-commit/61046953#61046953
        exclude: ^.vscode/
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: name-tests-test
        args:
          - "--django"
        description: "Tests should start with test_"
        exclude: "oauto_import_helper.py"
      - id: no-commit-to-branch
        args:
          - "--branch=main"
          - "--branch=release/dev"
          - "--branch=release/staging"
          - "--branch=release/prod"
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce # frozen: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
        exclude: "src/packages/oauto/oauto_external.py"
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  # ------------------------------------------------
  # JUPYTER NOTEBOOK CHECKS
  # ------------------------------------------------

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 466430972380026b7f3ac178c871ebcc2c58c277 # frozen: 1.3.1
    hooks:
      - id: nbqa-check-ast

  - repo: https://github.com/kynan/nbstripout
    rev: dc3ee8e102fa4af0769a99064b5eb7d6d4097abb # frozen: 0.5.0
    hooks:
      - id: nbstripout

  # ------------------------------------------------
  # FORMATTING CHECKS
  # ------------------------------------------------

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 5e374fda194d7f7ce9eebbd582b2a5594838c85b # frozen: v2.6.2
    hooks:
      - id: prettier
        types:
          - yaml
        # https://github.com/pre-commit/pre-commit/issues/758#issuecomment-505935221
        entry: bash -c 'export OPENSSL_CONF=""'
        exclude_types: ['pdf', 'png', 'jpeg']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 3ad5e9834d138bc7d9f5a2e7d6485bab5484d0e1 # frozen: v5.10.1
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 1f4cc3b9e2a80aee39da9466b6c141f529294a42 # frozen: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies:
          - toml

  - repo: https://github.com/myint/docformatter
    rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a # frozen: v1.4
    hooks:
      - id: docformatter
        args:
          - "--in-place"

  # ------------------------------------------------
  # SECURITY CHECKS
  # ------------------------------------------------

  - repo: https://github.com/PyCQA/bandit
    rev: 1ed79063e3672a1c6d91ee27cb648e07a7465344 # frozen: 1.7.4
    hooks:
      - id: bandit
        args: ["--skip=B311"]
        # B311=blacklist: standard pseudo-random generators

  - repo: https://github.com/twu/skjold
    rev: 3083e73b65c5e5dfd21fa791a8269eaee0ac1fcd # frozen: v0.4.1
    hooks:
      - id: skjold
        files: "^requirements.txt$"
        stages:
          - manual

  - repo: local
    hooks:
      # TODO: fix that it needs a public file in any case and moreover encrypts it every time regardless
      # - id: git-secret
      #   name: Hides/encrypts all publicly visible data added via "git secret add"
      #   entry: bash -c 'git secret hide'
      #   language: system

      - id: pytest-check
        # Run pytest-hook manually: https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
        # Execute in git-bash: pre-commit run --hook-stage manual pytest-check
        name: Carry out "pytest" on a selection of unittests
        args: ["src/tests/pre_deploy"]
        pass_filenames: false
        entry: pytest
        language: python
        stages:
          - manual

      - id: no_crlf
        name: "Check that no files with CRLF line endings are committed"
        types: [text]
        args: ["--multiline"]
        entry: '\r$'
        exclude_types: ['pdf', 'png', 'jpeg']
        language: pygrep

      # ------------------------------------------------
      # LINT CHECKS
      # ------------------------------------------------

      - id: flake8
        name: flake8
        args: ["--ignore=W503,W504"]
        # W503=Line break occurred before a binary operator
        # W504=Line break occurred after a binary operator
        description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        entry: pylint
        args: ["--extension-pkg-whitelist=pydantic"]
        language: python
        types: [python]
        require_serial: true

  # ------------------------------------------------
  # PRE-COMMIT SELF CHECK CHECKS
  # ------------------------------------------------

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
